# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SELCAAnalysis
                                 A QGIS plugin
 This plugin analyzes the correlation between land cover changes and dependent variables such as population and GDRP, and provides probabilistic forecasting of future land cover patterns.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-27
        copyright            : (C) 2025 by Author
        email                : email@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import inspect
from .selca_analysis import SelcaAnalysis


# noinspection PyPep8Naming
def classFactory(iface):  

    # Initialize the main plugin class
    plugin = SelcaAnalysis(iface)

    return plugin


